[project]
name = "preciceconfigchecker"
version = "0.0.1"
dependencies = [
    "precice_config_graph @ git+https://github.com/precice-forschungsprojekt/config-graph.git",
    "pyprecice>=3.1.2",
    "pytest"
]

[tool.setuptools]
packages = ["preciceconfigchecker"]

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test.py", "*_test.py"]