[project]
name = "preciceconfigchecker"
version = "0.0.1"

readme = "README.md"
license = {text = "MIT License"}

requires-python = ">= 3.10"
dependencies = [
    "precice_config_graph @ git+https://github.com/precice-forschungsprojekt/config-graph.git",
    "pytest"
]

[project.urls]
Repository = "https://github.com/precice-forschungsprojekt/config-checker.git"
Issues = "https://github.com/precice-forschungsprojekt/config-checker/issues"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project.scripts]
precice-config-checker = "preciceconfigchecker.cli:main"

[tool.setuptools]
packages = ["preciceconfigchecker"]

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test.py", "*_test.py"]
pythonpath = ["."]
