name: Run Unit Test via Pytest

on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install preCICE
        run: |
          wget https://github.com/precice/precice/releases/download/v3.1.2/libprecice3_3.1.2_noble.deb
          sudo apt install ./libprecice3_3.1.2_noble.deb
      - name: Install dependencies
        run: |
          sudo apt install -y libopenmpi-dev
          python -m pip install --upgrade pip setuptools cython
          pip install .
      - name: Test with pytest
        run: |
          pytest -v -s